name: conduit_isolate_executor
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
version: 0.1.0
homepage: https://github.com/stablekernel/dart-isolate-executor
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  glob: ^2.0.0

dev_dependencies:
  test: ^1.6.5
  test_package:
    path: test/test_package
